# Generated by Django 3.2.4 on 2021-12-23 06:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import martor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('front_image', models.ImageField(blank=True, upload_to='article_front_img')),
                ('contents_ck', ckeditor.fields.RichTextField(blank=True)),
                ('contents_md', martor.models.MartorField(blank=True)),
                ('editor', models.CharField(max_length=2, verbose_name='Редактор статьи')),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры статьи')),
                ('reason_for_reject', models.CharField(blank=True, max_length=512, null=True, verbose_name='Причина снятия с публикации')),
                ('is_draft', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_moderation_in_progress', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sound', models.ImageField(blank=True, default='record_none.mp3', upload_to='media', verbose_name='Фотография профиля')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Хаб',
                'verbose_name_plural': 'Хабы',
            },
        ),
        migrations.CreateModel(
            name='ArticleViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP адрес')),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_view', to='mainapp.article')),
            ],
            options={
                'verbose_name': 'Просмотр статьи',
                'verbose_name_plural': 'Просмотры статьи',
            },
        ),
    ]
